<?php

namespace Database\Seeders;

trait CountriesList
{
    public static function countries(): array
    {
        return [
            'AUSTRIA',
            'BELGICA',
            'BULGARIA',
            'CHIPRE',
            'DINAMARCA',
            'ESPAÑA',
            'FINLANDIA',
            'FRANCIA',
            'GRECIA',
            'HUNGRIA',
            'IRLANDA',
            'ITALIA',
            'LUXEMBURGO',
            'MALTA',
            'PAISES BAJOS',
            'POLONIA',
            'PORTUGAL',
            'REINO UNIDO',
            'ALEMANIA',
            'RUMANIA',
            'SUECIA',
            'LETONIA',
            'ESTONIA',
            'LITUANIA',
            'REPUBLICA CHECA',
            'REPUBLICA ESLOVACA',
            'ESLOVENIA',
            'OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA',
            'ALBANIA',
            'ISLANDIA',
            'LIECHTENSTEIN',
            'MONACO',
            'NORUEGA',
            'ANDORRA',
            'SAN MARINO',
            'SANTA SEDE',
            'SUIZA',
            'UCRANIA',
            'MOLDAVIA',
            'BELARUS',
            'GEORGIA',
            'BOSNIA Y HERZEGOVINA',
            'CROACIA',
            'ARMENIA',
            'RUSIA',
            'MACEDONIA ',
            'SERBIA',
            'MONTENEGRO',
            'GUERNESEY',
            'SVALBARD Y JAN MAYEN',
            'ISLAS FEROE',
            'ISLA DE MAN',
            'GIBRALTAR',
            'ISLAS DEL CANAL',
            'JERSEY',
            'ISLAS ALAND',
            'TURQUIA',
            'OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA',
            'BURKINA FASO',
            'ANGOLA',
            'ARGELIA',
            'BENIN',
            'BOTSWANA',
            'BURUNDI',
            'CABO VERDE',
            'CAMERUN',
            'COMORES',
            'CONGO',
            'COSTA DE MARFIL',
            'DJIBOUTI',
            'EGIPTO',
            'ETIOPIA',
            'GABON',
            'GAMBIA',
            'GHANA',
            'GUINEA',
            'GUINEA-BISSAU',
            'GUINEA ECUATORIAL',
            'KENIA',
            'LESOTHO',
            'LIBERIA',
            'LIBIA',
            'MADAGASCAR',
            'MALAWI',
            'MALI',
            'MARRUECOS',
            'MAURICIO',
            'MAURITANIA',
            'MOZAMBIQUE',
            'NAMIBIA',
            'NIGER',
            'NIGERIA',
            'REPUBLICA CENTROAFRICANA',
            'SUDAFRICA',
            'RUANDA',
            'SANTO TOME Y PRINCIPE',
            'SENEGAL',
            'SEYCHELLES',
            'SIERRA LEONA',
            'SOMALIA',
            'SUDAN',
            'SWAZILANDIA',
            'TANZANIA',
            'CHAD',
            'TOGO',
            'TUNEZ',
            'UGANDA',
            'REP.DEMOCRATICA DEL CONGO',
            'ZAMBIA',
            'ZIMBABWE',
            'ERITREA',
            'SANTA HELENA',
            'REUNION',
            'MAYOTTE',
            'SAHARA OCCIDENTAL',
            'OTROS PAISES O TERRITORIOS DE AFRICA',
            'CANADA',
            'ESTADOS UNIDOS DE AMERICA',
            'MEXICO',
            'SAN PEDRO Y MIQUELON ',
            'GROENLANDIA',
            'OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE'
        ];
    }
}